### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by paleo** [mika-fischer/napi-thread-safe-callback#10]
Thank you for the class `ThreadSafeCallback`, it works fine. I'd need something similar to create a `Napi::Promise::Deferred` on the main thread, but then resolve or reject it from another thread. Is it possible?

**Comment by mika-fischer** [comment]
Not nicely, I'm afraid. Of course, both the `arg_function` and the `completion_function` will be executed on the main thread, so you could resolve the promise in one of them. But you'd still need some dummy `Napi::Function` callback, which makes it a bit inelegant.

In general, please note that these things are now also implemented in napi directly: https://nodejs.org/dist/latest-v11.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls

**Comment by paleo** [comment]
OK, understood. Thanks.

**Comment by mika-fischer** [comment]
It might also be worthwhile to ask the people over at https://github.com/nodejs/node-addon-api how this could be done more elegantly. They're always interested in hearing from people who can't do what they want to do using napi...

**Comment by SurienDG** [comment]
@paleo @mika-fischer 

For a module that may make thread safe promises more seamless see: https://github.com/SurienDG/NAPI-Thread-Safe-Promise

**Comment by SurienDG** [comment]
@paleo  @mika-fischer 

This could be what you're looking for https://www.npmjs.com/package/napi_thread_safe_promise
