### ISSUE TITLE
Save the context of calling the js

### ISSUE THREAD

**Issue by aazavid** [mika-fischer/napi-thread-safe-callback#11]
How can I save the context of calling the js function inside my add-on, so that I can call it inside the add-on side of the c ++ function?

**Comment by mika-fischer** [comment]
If you don't wish to call the JS function from a different C++ thread, then you don't need this extension at all. N-API will suffice.

As for how N-API works in general, have a look at the examples: https://github.com/nodejs/node-addon-examples.

If by context you mean the receiver (the this value), then you can pass a Value as the first argument to Function::Call. See https://github.com/nodejs/node-addon-api/blob/master/doc/function.md#call-4

To keep the Value alive until you call the callback, see https://github.com/nodejs/node-addon-api/blob/master/doc/object_reference.md

I'm going to close this since the question is not very concrete and has possibly nothing to do with napi-thread-safe-callback. Feel free to reopen or create a new issue if you have more concrete questions.

**Comment by aazavid** [comment]
> To keep the Value alive until you call the callback, see https://github.com/nodejs/node-addon-api/blob/master/doc/object_reference.md

I want to save myself callback js, then to call him out of my lib. then when decides with C++ and not js. I'm tired of looking for a solution ( may be I do not understand how it works.

**Comment by mika-fischer** [comment]
This example here passes a JS callback to a C++ function and calls the callback from C++. Is this not what you want? https://github.com/nodejs/node-addon-examples/tree/master/3_callbacks/node-addon-api

**Comment by aazavid** [comment]
it calls js not with ++.  I want to subscribe in js to events in c++:
```
Napi::Value MyClass::onReady(const Napi::CallbackInfo& info){
  Napi::Env env = info.Env();
  Napi::HandleScope scope(env);

  this->cb =  info[0].As<Napi::Function>();
 this->Mydriver->cb = std::bind(&MyClass::ReadyInvoke, this, _1, _2);
 
  return info.Env().Undefined();
}

void MyClass::ReadyInvoke(int errorCode, device_handle result)
{

  // Create a new instance
 Napi::Object obj = Napi::Object::New(env);
 Napi::Number num = Napi::Number::New(env, errorCode);
 Napi::String str = Napi::String::New(env, result.Id);
 // Assign values to properties
 obj.Set("deviceId", str);
 this->cb.Call({num, obj });
 return info.Env().Undefined();
}
MyDriver::Search()
{
  /// do something
 if(flag) cb(errorcode, result)
}
```

I think I was able to convey my thought in code?

**Comment by mika-fischer** [comment]
Maybe this will help you get started.

```cpp
// This will be called from JS and will run in the JS main thread
void MyClass::onReady(const Napi::CallbackInfo& info) {
    cb = std::make_shared<ThreadSafeCallback>(info[0].As<Napi::Function>());
}

// This will run in a different thread
// Therefore it may not call any Napi:: functions
void MyDriver::Search() {
    int errorCode;
    device_handle result;
    bool flag;

    // TODO: do something to set errorCode, result and flag
    
    if (flag) {
        std::string id = result.Id;
        cb->call([errorCode, id](Napi::Env env, std::vector<napi_value>& args) {
            // This lambda will run in the JS main thread (at some time in the future)
            // Here we are allowed to use Napi:: functions again
            // We need to put the arguments for the callback in args
            // It is important that errorCode and id are captured by value so that
            // they are still available when the lambda is executed
            Napi::Object obj = Napi::Object::New(env);
            obj.Set("deviceId", Napi::String::New(env, id));
            args = { Napi::Number::New(env, errorCode), obj };
        });
        // cb->call will not wait until the callback is executed in JS. It will return immediately!
        // If you want to wait here until the JS callback was executed, then use operator(), i.e.
        // auto fut = (*cb)([errorCode, id](Napi::Env env, std::vector<napi_value>& args) { ... });
        // fut.get(); // This waits until the callback is finished
    }
}
```

**Comment by aazavid** [comment]
oo, great, now I understand how it works!) Thank you very much!)

**Comment by aazavid** [comment]
Does it work in an electron.js environment?

**Comment by mika-fischer** [comment]
I don't know, but I don't see any immediate readon why not if electron supports n-api...
