### ISSUE TITLE
Is this package ABI stable?

### ISSUE THREAD

**Issue by clarkttfu** [mika-fischer/napi-thread-safe-callback#12]
Hi, I found this package actually use libuv directly, and the N-API guide said I should stick with napi.h.
Excellent works anyway!!

**Comment by mika-fischer** [comment]
At the time I wrote this, there was just no other way. And there were some discussions about what parts of libuv (if any) should be considered stable. I don't know what came of these discussions.

However, nowadays this is supported directly in napi: https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls

**Comment by clarkttfu** [comment]
Actually I found those new APIs at first, but due to product limitation we have to stick with 8.x..
And I thought this package could be life saving. I will do some tests and let you know the result. 
Thank you anyway!

**Comment by mika-fischer** [comment]
FWIW, here's the discussion I mentioned: https://github.com/nodejs/node/issues/13512#issuecomment-347259489

**Comment by clarkttfu** [comment]
According to the descriptions, libuv is actually quite stable nowadays. IMHO, the N-API is to isolate the v8 changes. I have removed the dependency to this package from my code -- `uv_async_init` and `uv_async_send` are all I needed. And the build run without issue on 6.14.2 / 6.17.0 / 8.15.1 and 10.15.3.

So I guess this package should be ABI stable too, but I don't have time for those works.
