### ISSUE TITLE
Calls only once in windows, mac no problem

### ISSUE THREAD

**Issue by deshan** [mika-fischer/napi-thread-safe-callback#13]
Hi
I execute a ThreadSafeCallback repeatedly with a streaming data. But in windows environment it execute only once, the cpp function calls repeatedly but ThreadSafeCallback execute only once.

In mac environment this has no issues.

`
	
	class Callback {

	std::shared_ptr<ThreadSafeCallback> callback;
	
	Napi::Value runGStreamer(const Napi::CallbackInfo& info) {
		Napi::Env env = info.Env();
		Napi::HandleScope scope(env);
		
		callback = std::make_shared<ThreadSafeCallback>(info[0].As<Function>());
	}
	
	// Calls from a boost thread, calls each time it has data in a stream infinitely
	void hasData(Data &data) {
 		printf("has data\n");  // <- this get calls repeatedly
		// But below execute only once
		callback->call([data](Env env, std::vector<napi_value>& args) {
		args = { Napi::Number::New(env, data.size) };
	});
	}
}

`
What am i missing?

**Comment by mika-fischer** [comment]
Could you try:
I don't see anything that's obviously wrong with this...

Could you try:
```cpp
void hasData(Data &data)
    printf("hasData start\n");
    auto fut = (*callback)(
        [data](Env env, std::vector<napi_value>& args) {
            printf("hasData cb start\n");
            args = { Napi::Number::New(env, data.size) };
        },
        [](const Napi::Value&, const Napi::Error&) {
            printf("hasData cb return\n");
        });
    printf("hasData cb queued\n");
    fut.get();
    printf("hasData end\n");
}
```

**Comment by deshan** [comment]
Thanks for your quick reply,
I had compile error in the code you provided. Am I using different version? I'm using napi-thread-safe-callback": "0.0.6",
` error C3313: 'fut': variable cannot have the type 'void'`

But with slight modifications I managed to run this
```
void hasData(Data &data){
    printf("hasData start\n");
    auto fut = callback->call<bool>([data](Napi::Env env, std::vector<napi_value>& args) {
		args = { Napi::Number::New(env, data.size) };
	},
	[](const Napi::Value &val) {
		printf("hasData cb return\n");
		return val.As<Napi::Boolean>().Value();
	});
    printf("hasData cb queued\n");
    fut.get();
    printf("hasData end\n");
}
```
And as I seen first cycle goes without issues. But in the second cycle it freeze. Output
```
hasData
hasData cb queued
hasData cb return
hasData end
hasData
hasData cb queued
<Freeze After>
```

My js is an electron app.
I'm calling this like
```
napiWrapr.runMethod(function(size) {
	console.log('callback:', size);
	return true;
})
```
This still works perfectly in mac and ubuntu. Only in windows I have this.

**Comment by mika-fischer** [comment]
How about:
```cpp
void hasData(Data &data){
    printf("hasData start\n");
    auto fut = callback->call<bool>([data](Napi::Env env, std::vector<napi_value>& args) {
		args = { Napi::Number::New(env, data.size) };
                printf("hasData cb start\n");
	},
	[](const Napi::Value &val) {
		printf("hasData cb return\n");
		return val.As<Napi::Boolean>().Value();
	});
    printf("hasData cb queued\n");
    fut.get();
    printf("hasData end\n");
}
```

I.e. also print before the JS code is being run.

But I really have no clue what could be going wrong. I use this code on Windows, but I've never used Electron.

It would be good if you could write a small complete and self-contained example demonstrating the problem, or adapt a test to fail. See for instance https://github.com/mika-fischer/napi-thread-safe-callback/blob/master/test/tests.js#L300-L323 and https://github.com/mika-fischer/napi-thread-safe-callback/blob/master/test/tests.cpp#L150-L170

But it might be even better to use the NAPI-native solution instead: https://github.com/nodejs/node-addon-api/blob/master/napi.h#L2065

**Comment by deshan** [comment]
Thanks

This is unusual
In the first run from command prompt. The output is

> hasData
> hasData cb queued
> hasData cb start
> hasData cb return
> hasData end
> hasData
> hasData cb queued
> ...Freeze


From the second time start the  app by npm start
> hasData
> hasData cb queued
> ...Freeze

I will check NAPI-native solution, if you have anymore thoughts pls share

**Comment by deshan** [comment]
Not a problem here. When trying without electron no issues.
closing.
Thanks @mika-fischer
