### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Kekec852** [mika-fischer/napi-thread-safe-callback#6]
Hi, 

i have builld fail o with node@10.2.1 (node-gyp@3.6.2).

```
napi-thread-safe-callback-impl.hpp(183): error C2668: 'ThreadSafeCallback::operator ()': ambiguous call to overloaded function
```
On node@9.9.0 code compiles as expected.

**Comment by mika-fischer** [comment]
I can't reproduce this with current Node.js 10: https://ci.appveyor.com/project/mika-fischer/napi-thread-safe-callback

Please reopen if you continue to have this problem with more a detailed description on how to reproduce the issue.
